# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QhMqR3wB2agAZQTV_magVkts3VjNfskV
"""

# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBbkGyVQyVOucnXqy-00i6HAGoqIKCjf
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import io

# ─────────────────────────────────────────────
# PAGE CONFIGURATION
# ─────────────────────────────────────────────
st.set_page_config(
    page_title="HR Attrition Intelligence Dashboard",
    page_icon="🏢",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─────────────────────────────────────────────
# CUSTOM CSS  –  glassmorphism / dark-gradient theme
# ─────────────────────────────────────────────
st.markdown("""
<style>
/* ── Main background ── */
.stApp {
    background: linear-gradient(135deg, #0f0c29, #302b63, #24243e);
    color: #f0f0f0;
}

/* ── Sidebar ── */
[data-testid="stSidebar"] {
    background: rgba(255,255,255,0.05);
    backdrop-filter: blur(12px);
    border-right: 1px solid rgba(255,255,255,0.1);
}

/* ── Metric cards ── */
[data-testid="stMetric"] {
    background: rgba(255,255,255,0.08);
    border-radius: 16px;
    padding: 18px 22px;
    border: 1px solid rgba(255,255,255,0.15);
    backdrop-filter: blur(8px);
    box-shadow: 0 4px 30px rgba(0,0,0,0.3);
}
[data-testid="stMetricLabel"]  { color: #a0aec0 !important; font-size: 0.80rem; }
[data-testid="stMetricValue"]  { color: #ffffff !important; font-size: 2rem; font-weight: 700; }
[data-testid="stMetricDelta"]  { color: #68d391 !important; }

/* ── Section headers ── */
.section-header {
    font-size: 1.15rem;
    font-weight: 700;
    color: #a78bfa;
    letter-spacing: 1px;
    text-transform: uppercase;
    margin-bottom: 8px;
    border-left: 4px solid #7c3aed;
    padding-left: 10px;
}

/* ── Tabs ── */
.stTabs [data-baseweb="tab-list"] {
    background: rgba(255,255,255,0.05);
    border-radius: 12px;
    padding: 4px;
}
.stTabs [data-baseweb="tab"] {
    color: #a0aec0;
    border-radius: 10px;
    padding: 6px 20px;
}
.stTabs [aria-selected="true"] {
    background: rgba(124,58,237,0.5) !important;
    color: white !important;
}

/* ── Dataframe ── */
.stDataFrame { border-radius: 12px; overflow: hidden; }

/* ── Divider ── */
hr { border-color: rgba(255,255,255,0.1); }

/* ── Buttons ── */
.stButton > button {
    background: linear-gradient(135deg, #7c3aed, #4f46e5);
    color: white;
    border: none;
    border-radius: 10px;
    padding: 10px 22px;
    font-weight: 600;
    transition: transform .15s;
}
.stButton > button:hover { transform: translateY(-2px); }

/* ── Selectbox / slider labels ── */
label { color: #c4b5fd !important; font-weight: 600; }
</style>
""", unsafe_allow_html=True)

# ─────────────────────────────────────────────
# EMBEDDED DATASET  (first 10 rows shown; full data loaded via CSV text below)
# ─────────────────────────────────────────────
CSV_DATA = """Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Yes,11,3,1,0,8,0,1,6,4,0,5
49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,No,23,4,4,1,10,3,3,10,7,1,7
37,1,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Yes,15,3,2,0,7,3,3,0,0,0,0
33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Yes,11,3,3,0,8,3,3,8,7,3,0
27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,No,12,3,4,1,6,3,3,2,2,2,2
32,0,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,4,Male,79,3,1,Laboratory Technician,4,Single,3068,11864,0,No,13,3,3,0,8,2,2,7,7,3,6
59,0,Travel_Rarely,1324,Research & Development,3,3,Medical,3,Female,81,4,1,Laboratory Technician,1,Married,2670,9964,4,Yes,20,4,1,3,12,3,2,1,0,0,0
30,0,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,4,Male,67,3,1,Laboratory Technician,3,Divorced,2693,13335,1,No,22,4,2,1,1,2,3,1,0,0,0
38,0,Travel_Frequently,216,Research & Development,23,3,Life Sciences,4,Male,44,2,3,Manufacturing Director,3,Single,9526,8787,0,No,21,4,2,0,10,2,3,9,7,1,8
36,0,Travel_Rarely,1299,Research & Development,27,3,Medical,3,Male,94,3,2,Healthcare Representative,3,Married,5237,16577,6,No,13,3,2,2,17,3,2,7,7,7,7
35,0,Travel_Rarely,809,Research & Development,16,3,Medical,1,Male,84,4,1,Laboratory Technician,2,Married,2426,16479,0,No,13,3,3,1,6,5,3,5,4,0,3
29,0,Travel_Rarely,153,Research & Development,15,2,Life Sciences,4,Female,49,2,2,Laboratory Technician,3,Single,4193,12682,0,Yes,12,3,4,0,10,3,3,9,5,0,8
31,0,Travel_Rarely,670,Research & Development,26,1,Life Sciences,1,Male,31,3,1,Research Scientist,3,Divorced,2911,15170,1,No,17,3,4,1,5,1,2,5,2,4,3
34,0,Travel_Rarely,1346,Research & Development,19,2,Medical,2,Male,93,3,1,Laboratory Technician,4,Divorced,2661,8758,0,No,11,3,3,1,3,2,3,2,2,1,2
28,1,Travel_Rarely,103,Research & Development,24,3,Life Sciences,3,Male,50,2,1,Laboratory Technician,3,Single,2028,12947,5,Yes,14,3,2,0,6,4,3,4,2,0,3
29,0,Travel_Rarely,1389,Research & Development,21,4,Life Sciences,2,Female,51,4,3,Manufacturing Director,1,Divorced,9980,10195,1,No,11,3,3,1,10,1,3,10,9,8,8
32,0,Travel_Rarely,334,Research & Development,5,2,Life Sciences,1,Male,80,4,1,Research Scientist,2,Divorced,3298,15053,0,Yes,12,3,4,2,7,5,2,6,2,0,5
22,0,Non-Travel,1123,Research & Development,16,2,Medical,4,Male,96,4,1,Laboratory Technician,4,Divorced,2935,7324,1,Yes,13,3,2,2,1,2,2,1,0,0,0
53,0,Travel_Rarely,1219,Sales,2,4,Life Sciences,1,Female,78,2,4,Manager,4,Married,15427,22021,2,No,16,3,3,0,31,3,3,25,8,3,7
38,0,Travel_Rarely,371,Research & Development,2,3,Life Sciences,4,Male,45,3,1,Research Scientist,4,Single,3944,4306,5,Yes,11,3,3,0,6,3,3,3,2,1,2
24,0,Non-Travel,673,Research & Development,11,2,Other,1,Female,96,4,2,Manufacturing Director,3,Divorced,4011,8232,0,No,18,3,4,1,5,5,2,4,2,1,3
36,1,Travel_Rarely,1218,Sales,9,4,Life Sciences,3,Male,82,2,1,Sales Representative,1,Single,3407,6986,7,No,23,4,2,0,10,4,3,5,3,0,3
34,0,Travel_Rarely,419,Research & Development,7,4,Life Sciences,1,Female,53,3,3,Research Director,2,Single,11994,21293,0,No,11,3,3,0,13,4,3,12,6,2,11
21,0,Travel_Rarely,391,Research & Development,15,2,Life Sciences,3,Male,96,3,1,Research Scientist,4,Single,1232,19281,1,No,14,3,4,0,0,6,3,0,0,0,0
34,1,Travel_Rarely,699,Research & Development,6,1,Medical,2,Male,83,3,1,Research Scientist,1,Single,2960,17102,2,No,11,3,3,0,8,2,3,4,2,1,3
53,0,Travel_Rarely,1282,Research & Development,5,3,Other,3,Female,58,3,5,Manager,3,Divorced,19094,10735,4,No,11,3,4,1,26,3,2,14,13,4,8
32,1,Travel_Frequently,1125,Research & Development,16,1,Life Sciences,2,Female,72,1,1,Research Scientist,1,Single,3919,4681,1,Yes,22,4,2,0,10,5,3,10,2,6,7
42,0,Travel_Rarely,691,Sales,8,4,Marketing,3,Male,48,3,2,Sales Executive,2,Married,6825,21173,0,No,11,3,4,1,10,2,3,9,7,4,2
44,0,Travel_Rarely,477,Research & Development,7,4,Medical,1,Female,42,2,3,Healthcare Representative,4,Married,10248,2094,3,No,14,3,4,1,24,4,3,22,6,5,17
46,0,Travel_Rarely,705,Sales,2,4,Marketing,2,Female,83,3,5,Manager,1,Single,18947,22822,3,No,12,3,4,0,22,2,2,2,2,2,1
33,0,Travel_Rarely,924,Research & Development,2,3,Medical,3,Male,78,3,1,Laboratory Technician,4,Single,2496,6670,4,No,11,3,4,0,7,3,3,1,1,0,0
44,0,Travel_Rarely,1459,Research & Development,10,4,Other,4,Male,41,3,2,Healthcare Representative,4,Married,6465,19121,2,Yes,13,3,4,0,9,5,4,4,2,1,3
30,0,Travel_Rarely,125,Research & Development,9,2,Medical,4,Male,83,2,1,Laboratory Technician,3,Single,2206,16117,1,No,13,3,1,0,10,5,3,10,0,1,8
39,1,Travel_Rarely,895,Sales,5,3,Technical Degree,4,Male,56,3,2,Sales Representative,4,Married,2086,3335,3,No,14,3,3,1,19,6,4,1,0,0,0
24,1,Travel_Rarely,813,Research & Development,1,3,Medical,2,Male,61,3,1,Research Scientist,4,Married,2293,3020,2,Yes,16,3,1,1,6,2,2,2,0,2,0
43,0,Travel_Rarely,1273,Research & Development,2,2,Medical,4,Female,72,4,1,Research Scientist,3,Divorced,2645,21923,1,No,12,3,4,2,6,3,2,5,3,1,4
50,1,Travel_Rarely,869,Sales,3,2,Marketing,1,Male,86,2,1,Sales Representative,3,Married,2683,3810,1,Yes,14,3,3,0,3,2,3,3,2,0,2
35,0,Travel_Rarely,890,Sales,2,3,Marketing,4,Female,97,3,1,Sales Representative,4,Married,2014,9687,1,No,13,3,1,0,2,3,3,2,2,2,2
36,0,Travel_Rarely,852,Research & Development,5,4,Life Sciences,2,Female,82,2,1,Research Scientist,1,Married,3419,13072,9,Yes,14,3,4,1,6,3,4,1,1,0,0
33,0,Travel_Frequently,1141,Sales,1,3,Life Sciences,3,Female,42,4,2,Sales Executive,1,Married,5376,3193,2,No,19,3,1,2,10,3,3,5,3,1,3
35,0,Travel_Rarely,464,Research & Development,4,2,Other,3,Male,75,3,1,Laboratory Technician,4,Divorced,1951,10910,1,No,12,3,3,1,1,3,3,1,0,0,0
27,0,Travel_Rarely,1240,Research & Development,2,4,Life Sciences,4,Female,33,3,1,Laboratory Technician,1,Divorced,2341,19715,1,No,13,3,4,1,1,6,3,1,0,0,0
26,1,Travel_Rarely,1357,Research & Development,25,3,Life Sciences,1,Male,48,1,1,Laboratory Technician,3,Single,2293,10558,1,No,12,3,3,0,1,2,2,1,0,0,1
27,0,Travel_Frequently,994,Sales,8,3,Life Sciences,4,Male,37,3,3,Sales Executive,3,Single,8726,2975,1,No,15,3,4,0,9,0,3,9,8,1,7
30,0,Travel_Frequently,721,Research & Development,1,2,Medical,3,Female,58,3,2,Laboratory Technician,4,Single,4011,10781,1,No,23,4,4,0,12,2,3,12,8,3,7
41,1,Travel_Rarely,1360,Research & Development,12,3,Technical Degree,2,Female,49,3,5,Research Director,3,Married,19545,16280,1,No,12,3,4,0,23,0,3,22,15,15,8
34,0,Non-Travel,1065,Sales,23,4,Marketing,2,Male,72,3,2,Sales Executive,3,Single,4568,10034,0,No,20,4,3,0,10,2,3,9,5,8,7
37,0,Travel_Rarely,408,Research & Development,19,2,Life Sciences,2,Male,73,3,1,Research Scientist,2,Married,3022,10227,4,No,21,4,1,0,8,1,3,1,0,0,0
46,0,Travel_Frequently,1211,Sales,5,4,Marketing,1,Male,98,3,2,Sales Executive,4,Single,5772,20445,4,Yes,21,4,3,0,14,4,3,9,6,0,8
35,0,Travel_Rarely,1229,Research & Development,8,1,Life Sciences,4,Male,36,4,1,Laboratory Technician,4,Married,2269,4892,1,No,19,3,4,0,1,2,3,1,0,0,1"""

# ─────────────────────────────────────────────
# LOAD DATA
# ─────────────────────────────────────────────
@st.cache_data
def load_data(csv_text: str) -> pd.DataFrame:
    df = pd.read_csv(io.StringIO(csv_text))
    df["Attrition_Label"] = df["Attrition"].map({1: "Yes", 0: "No"})
    df["AgeGroup"] = pd.cut(
        df["Age"],
        bins=[17, 25, 35, 45, 60],
        labels=["18-25", "26-35", "36-45", "46-60"],
    )
    df["IncomeGroup"] = pd.cut(
        df["MonthlyIncome"],
        bins=[0, 3000, 6000, 10000, 25000],
        labels=["<3K", "3K-6K", "6K-10K", ">10K"],
    )
    return df

df = load_data(CSV_DATA)

# ─────────────────────────────────────────────
# COLOUR PALETTE
# ─────────────────────────────────────────────
PURPLE     = "#7c3aed"
PINK       = "#ec4899"
TEAL       = "#06b6d4"
AMBER      = "#f59e0b"
GREEN      = "#10b981"
RED        = "#ef4444"
PLOTLY_BG  = "rgba(0,0,0,0)"
TEXT_COLOR = "#e2e8f0"

ATTRITION_COLORS = {"Yes": RED, "No": GREEN}
DEPT_COLORS = px.colors.qualitative.Vivid

def style_fig(fig, height=380):
    """Apply dark, transparent styling to all Plotly figures."""
    fig.update_layout(
        height=height,
        paper_bgcolor=PLOTLY_BG,
        plot_bgcolor="rgba(255,255,255,0.03)",
        font=dict(color=TEXT_COLOR, family="Inter, sans-serif", size=12),
        margin=dict(l=20, r=20, t=40, b=20),
        legend=dict(
            bgcolor="rgba(255,255,255,0.05)",
            bordercolor="rgba(255,255,255,0.15)",
            borderwidth=1,
            font=dict(size=11),
        ),
        xaxis=dict(gridcolor="rgba(255,255,255,0.07)", zeroline=False),
        yaxis=dict(gridcolor="rgba(255,255,255,0.07)", zeroline=False),
    )
    return fig

# ─────────────────────────────────────────────
# ── SIDEBAR ──
# ─────────────────────────────────────────────
with st.sidebar:
    st.markdown("## 🏢 HR Intelligence")
    st.markdown("---")

    st.markdown("### 🎯 Filters")

    dept_opts = ["All"] + sorted(df["Department"].unique().tolist())
    dept_sel  = st.selectbox("Department", dept_opts)

    gender_opts = ["All"] + sorted(df["Gender"].unique().tolist())
    gender_sel  = st.selectbox("Gender", gender_opts)

    marital_opts = ["All"] + sorted(df["MaritalStatus"].unique().tolist())
    marital_sel  = st.selectbox("Marital Status", marital_opts)

    travel_opts = ["All"] + sorted(df["BusinessTravel"].unique().tolist())
    travel_sel  = st.selectbox("Business Travel", travel_opts)

    age_range = st.slider("Age Range", int(df["Age"].min()), int(df["Age"].max()),
                          (int(df["Age"].min()), int(df["Age"].max())))

    income_range = st.slider("Monthly Income ($)",
                             int(df["MonthlyIncome"].min()),
                             int(df["MonthlyIncome"].max()),
                             (int(df["MonthlyIncome"].min()), int(df["MonthlyIncome"].max())))

    overtime_opts = ["All", "Yes", "No"]
    overtime_sel  = st.selectbox("OverTime", overtime_opts)

    st.markdown("---")
    st.markdown("### 📊 About")
    st.info("Interactive HR Attrition Dashboard — built with Streamlit & Plotly.\n\nUse the filters to drill into any segment.")

# ─────────────────────────────────────────────
# APPLY FILTERS
# ─────────────────────────────────────────────
fdf = df.copy()
if dept_sel   != "All": fdf = fdf[fdf["Department"]     == dept_sel]
if gender_sel != "All": fdf = fdf[fdf["Gender"]         == gender_sel]
if marital_sel!= "All": fdf = fdf[fdf["MaritalStatus"]  == marital_sel]
if travel_sel != "All": fdf = fdf[fdf["BusinessTravel"] == travel_sel]
if overtime_sel!="All": fdf = fdf[fdf["OverTime"]       == overtime_sel]
fdf = fdf[(fdf["Age"].between(*age_range)) & (fdf["MonthlyIncome"].between(*income_range))]

total          = len(fdf)
attrited       = fdf["Attrition"].sum()
attr_rate      = attrited / total * 100 if total else 0
avg_income     = fdf["MonthlyIncome"].mean()
avg_age        = fdf["Age"].mean()
avg_tenure     = fdf["YearsAtCompany"].mean()
overtime_pct   = (fdf["OverTime"] == "Yes").mean() * 100
avg_satisfaction = fdf["JobSatisfaction"].mean()

# ─────────────────────────────────────────────
# TITLE
# ─────────────────────────────────────────────
st.markdown("""
<div style='text-align:center; padding: 20px 0 10px 0;'>
    <h1 style='font-size:2.4rem; font-weight:800;
               background: linear-gradient(90deg, #a78bfa, #ec4899, #06b6d4);
               -webkit-background-clip: text; -webkit-text-fill-color: transparent;
               margin-bottom:4px;'>
        🏢 HR Attrition Intelligence Dashboard
    </h1>
    <p style='color:#94a3b8; font-size:1rem; margin:0;'>
        Real-time workforce analytics · Powered by Streamlit & Plotly
    </p>
</div>
""", unsafe_allow_html=True)
st.markdown("---")

# ─────────────────────────────────────────────
# KPI ROW
# ─────────────────────────────────────────────
k1, k2, k3, k4, k5, k6, k7 = st.columns(7)
k1.metric("👥 Employees",       f"{total:,}")
k2.metric("🚪 Attrition Rate",  f"{attr_rate:.1f}%",  f"{attr_rate-16.1:.1f}% vs. bench")
k3.metric("💰 Avg Income",      f"${avg_income:,.0f}")
k4.metric("📅 Avg Age",         f"{avg_age:.1f} yrs")
k5.metric("🏠 Avg Tenure",      f"{avg_tenure:.1f} yrs")
k6.metric("⏰ Overtime %",      f"{overtime_pct:.1f}%")
k7.metric("😊 Job Satisfaction",f"{avg_satisfaction:.2f}/4")

st.markdown("")

# ─────────────────────────────────────────────
# TABS
# ─────────────────────────────────────────────
tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "📊 Overview",
    "🔍 Attrition Deep-Dive",
    "💼 Workforce Profile",
    "💲 Compensation",
    "🗄️ Data Explorer",
])

# ════════════════════════════════════════════
# TAB 1  –  OVERVIEW
# ════════════════════════════════════════════
with tab1:
    col_a, col_b, col_c = st.columns([1.2, 1.2, 1])

    # ── Attrition donut ──
    with col_a:
        st.markdown('<p class="section-header">Attrition Split</p>', unsafe_allow_html=True)
        counts = fdf["Attrition_Label"].value_counts().reset_index()
        counts.columns = ["Status", "Count"]
        fig_donut = px.pie(
            counts, names="Status", values="Count", hole=0.6,
            color="Status", color_discrete_map=ATTRITION_COLORS,
        )
        fig_donut.update_traces(textinfo="percent+label", pull=[0.05, 0])
        fig_donut.add_annotation(
            text=f"<b>{attr_rate:.1f}%</b><br>Attrition",
            x=0.5, y=0.5, showarrow=False,
            font=dict(size=18, color=TEXT_COLOR),
        )
        st.plotly_chart(style_fig(fig_donut, 350), width="stretch")

    # ── Department bar ──
    with col_b:
        st.markdown('<p class="section-header">Attrition by Department</p>', unsafe_allow_html=True)
        dept_attr = (
            fdf.groupby(["Department", "Attrition_Label"])
            .size().reset_index(name="Count")
        )
        fig_dept = px.bar(
            dept_attr, x="Department", y="Count",
            color="Attrition_Label", barmode="stack",
            color_discrete_map=ATTRITION_COLORS,
            text="Count",
        )
        fig_dept.update_traces(textposition="inside", textfont_size=10)
        fig_dept.update_layout(xaxis_title="", yaxis_title="Headcount", showlegend=True)
        st.plotly_chart(style_fig(fig_dept, 350), width="stretch")

    # ── Gauge – Satisfaction ──
    with col_c:
        st.markdown('<p class="section-header">Avg Job Satisfaction</p>', unsafe_allow_html=True)
        fig_gauge = go.Figure(go.Indicator(
            mode="gauge+number+delta",
            value=avg_satisfaction,
            delta={"reference": 2.5, "increasing": {"color": GREEN}},
            gauge={
                "axis": {"range": [1, 4], "tickfont": {"color": TEXT_COLOR}},
                "bar": {"color": PURPLE},
                "steps": [
                    {"range": [1, 2], "color": "rgba(239,68,68,0.3)"},
                    {"range": [2, 3], "color": "rgba(245,158,11,0.3)"},
                    {"range": [3, 4], "color": "rgba(16,185,129,0.3)"},
                ],
                "threshold": {"line": {"color": PINK, "width": 3}, "value": 2.5},
            },
            number={"font": {"size": 40, "color": TEXT_COLOR}},
            title={"text": "Score (1-4)", "font": {"size": 14, "color": "#94a3b8"}},
        ))
        st.plotly_chart(style_fig(fig_gauge, 350), width="stretch")

    st.markdown("---")

    col_d, col_e = st.columns(2)

    # ── Age group attrition ──
    with col_d:
        st.markdown('<p class="section-header">Attrition Rate by Age Group</p>', unsafe_allow_html=True)
        age_grp = (
            fdf.groupby("AgeGroup")["Attrition"]
            .agg(["sum", "count"])
            .reset_index()
        )
        age_grp["Rate"] = age_grp["sum"] / age_grp["count"] * 100
        fig_age = px.bar(
            age_grp, x="AgeGroup", y="Rate",
            color="Rate",
            color_continuous_scale=["#10b981", "#f59e0b", "#ef4444"],
            text=age_grp["Rate"].round(1).astype(str) + "%",
        )
        fig_age.update_traces(textposition="outside")
        fig_age.update_layout(coloraxis_showscale=False, yaxis_title="Attrition %")
        st.plotly_chart(style_fig(fig_age), width="stretch")

    # ── JobRole attrition heatmap ──
    with col_e:
        st.markdown('<p class="section-header">Attrition by Job Role & Gender</p>', unsafe_allow_html=True)
        heat = (
            fdf.groupby(["JobRole", "Gender"])["Attrition"]
            .mean().mul(100).round(1).reset_index()
        )
        heat_pivot = heat.pivot(index="JobRole", columns="Gender", values="Attrition").fillna(0)
        fig_heat = px.imshow(
            heat_pivot,
            color_continuous_scale="RdBu_r",
            text_auto=True,
            aspect="auto",
        )
        fig_heat.update_layout(coloraxis_colorbar=dict(title="% Attr"))
        st.plotly_chart(style_fig(fig_heat), width="stretch")

# ════════════════════════════════════════════
# TAB 2  –  ATTRITION DEEP-DIVE
# ════════════════════════════════════════════
with tab2:
    col1, col2 = st.columns(2)

    # ── Marital status ──
    with col1:
        st.markdown('<p class="section-header">Attrition by Marital Status</p>', unsafe_allow_html=True)
        ms = (
            fdf.groupby(["MaritalStatus", "Attrition_Label"])
            .size().reset_index(name="Count")
        )
        fig_ms = px.bar(
            ms, x="MaritalStatus", y="Count",
            color="Attrition_Label", barmode="group",
            color_discrete_map=ATTRITION_COLORS,
        )
        st.plotly_chart(style_fig(fig_ms), width="stretch")

    # ── Business travel ──
    with col2:
        st.markdown('<p class="section-header">Attrition by Business Travel</p>', unsafe_allow_html=True)
        bt = (
            fdf.groupby(["BusinessTravel", "Attrition_Label"])
            .size().reset_index(name="Count")
        )
        fig_bt = px.bar(
            bt, x="BusinessTravel", y="Count",
            color="Attrition_Label", barmode="group",
            color_discrete_map=ATTRITION_COLORS,
        )
        st.plotly_chart(style_fig(fig_bt), width="stretch")

    col3, col4 = st.columns(2)

    # ── Overtime effect ──
    with col3:
        st.markdown('<p class="section-header">Overtime vs Attrition</p>', unsafe_allow_html=True)
        ot = (
            fdf.groupby(["OverTime", "Attrition_Label"])
            .size().reset_index(name="Count")
        )
        ot_total = ot.groupby("OverTime")["Count"].transform("sum")
        ot["Pct"] = (ot["Count"] / ot_total * 100).round(1)
        fig_ot = px.bar(
            ot, x="OverTime", y="Pct",
            color="Attrition_Label", barmode="stack",
            color_discrete_map=ATTRITION_COLORS,
            text=ot["Pct"].astype(str) + "%",
        )
        fig_ot.update_traces(textposition="inside")
        fig_ot.update_layout(yaxis_title="% of Group")
        st.plotly_chart(style_fig(fig_ot), width="stretch")

    # ── Years at company violin ──
    with col4:
        st.markdown('<p class="section-header">Tenure Distribution by Attrition</p>', unsafe_allow_html=True)
        fig_vio = px.violin(
            fdf, x="Attrition_Label", y="YearsAtCompany",
            color="Attrition_Label", box=True, points="outliers",
            color_discrete_map=ATTRITION_COLORS,
        )
        fig_vio.update_layout(xaxis_title="Attrition", yaxis_title="Years at Company")
        st.plotly_chart(style_fig(fig_vio), width="stretch")

    # ── Radar: mean satisfaction scores ──
    st.markdown('<p class="section-header">Satisfaction Radar — Attrited vs Retained</p>', unsafe_allow_html=True)
    radar_cols = ["EnvironmentSatisfaction", "JobSatisfaction",
                  "RelationshipSatisfaction", "WorkLifeBalance", "JobInvolvement"]
    radar_df = (
        fdf.groupby("Attrition_Label")[radar_cols]
        .mean().reset_index()
    )
    fig_radar = go.Figure()
    for _, row in radar_df.iterrows():
        color = RED if row["Attrition_Label"] == "Yes" else GREEN
        fig_radar.add_trace(go.Scatterpolar(
            r=row[radar_cols].tolist() + [row[radar_cols[0]]],
            theta=radar_cols + [radar_cols[0]],
            fill="toself",
            name=row["Attrition_Label"],
            line_color=color,
            fillcolor="rgba(16,185,129,0.15)" if row["Attrition_Label"] == "No" else "rgba(239,68,68,0.15)",
        ))
    fig_radar.update_layout(
        polar=dict(
            bgcolor="rgba(255,255,255,0.03)",
            radialaxis=dict(visible=True, range=[1, 4], gridcolor="rgba(255,255,255,0.1)"),
            angularaxis=dict(gridcolor="rgba(255,255,255,0.1)"),
        )
    )
    st.plotly_chart(style_fig(fig_radar, 420), width="stretch")

# ════════════════════════════════════════════
# TAB 3  –  WORKFORCE PROFILE
# ════════════════════════════════════════════
with tab3:
    c1, c2 = st.columns(2)

    # ── Age histogram ──
    with c1:
        st.markdown('<p class="section-header">Age Distribution</p>', unsafe_allow_html=True)
        fig_ah = px.histogram(
            fdf, x="Age", color="Attrition_Label",
            nbins=20, barmode="overlay", opacity=0.7,
            color_discrete_map=ATTRITION_COLORS,
        )
        fig_ah.update_layout(bargap=0.05, xaxis_title="Age", yaxis_title="Count")
        st.plotly_chart(style_fig(fig_ah), width="stretch")

    # ── Education sunburst ──
    with c2:
        st.markdown('<p class="section-header">Education Field × Department</p>', unsafe_allow_html=True)
        sun_df = fdf.groupby(["Department", "EducationField"]).size().reset_index(name="Count")
        fig_sun = px.sunburst(
            sun_df, path=["Department", "EducationField"], values="Count",
            color="Department", color_discrete_sequence=DEPT_COLORS,
        )
        st.plotly_chart(style_fig(fig_sun, 380), width="stretch")

    c3, c4 = st.columns(2)

    # ── Job level stacked ──
    with c3:
        st.markdown('<p class="section-header">Job Level Distribution</p>', unsafe_allow_html=True)
        jl = fdf.groupby(["JobLevel", "Department"]).size().reset_index(name="Count")
        fig_jl = px.bar(
            jl, x="JobLevel", y="Count", color="Department",
            color_discrete_sequence=DEPT_COLORS, barmode="stack",
        )
        fig_jl.update_layout(xaxis_title="Job Level", yaxis_title="Headcount")
        st.plotly_chart(style_fig(fig_jl), width="stretch")

    # ── Training times ──
    with c4:
        st.markdown('<p class="section-header">Training Times Last Year</p>', unsafe_allow_html=True)
        tr = fdf.groupby(["TrainingTimesLastYear", "Attrition_Label"]).size().reset_index(name="Count")
        fig_tr = px.line(
            tr, x="TrainingTimesLastYear", y="Count",
            color="Attrition_Label", markers=True,
            color_discrete_map=ATTRITION_COLORS,
        )
        st.plotly_chart(style_fig(fig_tr), width="stretch")

    # ── Total working years vs years at company scatter ──
    st.markdown('<p class="section-header">Total Experience vs Tenure (bubble = Monthly Income)</p>', unsafe_allow_html=True)
    fig_sc = px.scatter(
        fdf.sample(min(len(fdf), 300), random_state=42),
        x="TotalWorkingYears", y="YearsAtCompany",
        size="MonthlyIncome", color="Attrition_Label",
        color_discrete_map=ATTRITION_COLORS,
        hover_data=["JobRole", "Department", "Age"],
        size_max=28, opacity=0.75,
    )
    fig_sc.update_layout(xaxis_title="Total Working Years", yaxis_title="Years at Company")
    st.plotly_chart(style_fig(fig_sc, 450), width="stretch")

# ════════════════════════════════════════════
# TAB 4  –  COMPENSATION
# ════════════════════════════════════════════
with tab4:
    c1, c2 = st.columns(2)

    # ── Box: income by role ──
    with c1:
        st.markdown('<p class="section-header">Monthly Income by Job Role</p>', unsafe_allow_html=True)
        fig_box = px.box(
            fdf.sort_values("MonthlyIncome"),
            x="MonthlyIncome", y="JobRole",
            color="Attrition_Label",
            color_discrete_map=ATTRITION_COLORS,
            orientation="h",
        )
        fig_box.update_layout(yaxis_title="", xaxis_title="Monthly Income ($)")
        st.plotly_chart(style_fig(fig_box, 450), width="stretch")

    # ── Salary hike vs performance ──
    with c2:
        st.markdown('<p class="section-header">Salary Hike % by Performance Rating</p>', unsafe_allow_html=True)
        ph = fdf.groupby(["PerformanceRating", "Attrition_Label"])["PercentSalaryHike"] \
               .mean().round(1).reset_index()
        fig_ph = px.bar(
            ph, x="PerformanceRating", y="PercentSalaryHike",
            color="Attrition_Label", barmode="group",
            color_discrete_map=ATTRITION_COLORS, text="PercentSalaryHike",
        )
        fig_ph.update_traces(texttemplate="%{text:.1f}%", textposition="outside")
        fig_ph.update_layout(xaxis_title="Performance Rating", yaxis_title="Avg Salary Hike %")
        st.plotly_chart(style_fig(fig_ph), width="stretch")

    c3, c4 = st.columns(2)

    # ── Stock option ──
    with c3:
        st.markdown('<p class="section-header">Stock Option Level & Attrition</p>', unsafe_allow_html=True)
        so = fdf.groupby(["StockOptionLevel", "Attrition_Label"]).size().reset_index(name="Count")
        so_tot = so.groupby("StockOptionLevel")["Count"].transform("sum")
        so["Pct"] = (so["Count"] / so_tot * 100).round(1)
        fig_so = px.bar(
            so, x="StockOptionLevel", y="Pct",
            color="Attrition_Label", barmode="stack",
            color_discrete_map=ATTRITION_COLORS,
            text=so["Pct"].astype(str) + "%",
        )
        fig_so.update_traces(textposition="inside")
        fig_so.update_layout(yaxis_title="% of Group", xaxis_title="Stock Option Level")
        st.plotly_chart(style_fig(fig_so), width="stretch")

    # ── Income group donut ──
    with c4:
        st.markdown('<p class="section-header">Income Band Distribution</p>', unsafe_allow_html=True)
        ig = fdf["IncomeGroup"].value_counts().reset_index()
        ig.columns = ["Band", "Count"]
        fig_ig = px.pie(
            ig, names="Band", values="Count", hole=0.5,
            color_discrete_sequence=[GREEN, TEAL, AMBER, RED],
        )
        fig_ig.update_traces(textinfo="percent+label")
        st.plotly_chart(style_fig(fig_ig, 350), width="stretch")

    # ── Correlation heatmap ──
    st.markdown('<p class="section-header">Numeric Feature Correlation Matrix</p>', unsafe_allow_html=True)
    num_cols = [
        "Age", "MonthlyIncome", "TotalWorkingYears", "YearsAtCompany",
        "YearsInCurrentRole", "JobSatisfaction", "EnvironmentSatisfaction",
        "PercentSalaryHike", "DistanceFromHome", "WorkLifeBalance", "Attrition",
    ]
    corr = fdf[num_cols].corr().round(2)
    fig_corr = px.imshow(
        corr, text_auto=True, aspect="auto",
        color_continuous_scale="RdBu_r", zmin=-1, zmax=1,
    )
    fig_corr.update_layout(height=450, coloraxis_colorbar=dict(title="r"))
    st.plotly_chart(style_fig(fig_corr, 450), width="stretch")

# ════════════════════════════════════════════
# TAB 5  –  DATA EXPLORER
# ════════════════════════════════════════════
with tab5:
    st.markdown('<p class="section-header">Filtered Employee Records</p>', unsafe_allow_html=True)

    col_search, col_sort, col_dir = st.columns([2, 2, 1])
    with col_search:
        search_text = st.text_input("🔎 Search (Job Role / Department / Gender)", "")
    with col_sort:
        sort_col = st.selectbox("Sort by", ["Age", "MonthlyIncome", "YearsAtCompany",
                                            "TotalWorkingYears", "PercentSalaryHike"])
    with col_dir:
        ascending = st.radio("Direction", ["⬆ Asc", "⬇ Desc"]) == "⬆ Asc"

    display_df = fdf.copy()
    if search_text:
        mask = (
            display_df["JobRole"].str.contains(search_text, case=False, na=False) |
            display_df["Department"].str.contains(search_text, case=False, na=False) |
            display_df["Gender"].str.contains(search_text, case=False, na=False)
        )
        display_df = display_df[mask]

    display_df = display_df.sort_values(sort_col, ascending=ascending)
    display_cols = ["Age", "Gender", "Department", "JobRole", "JobLevel",
                    "MonthlyIncome", "YearsAtCompany", "TotalWorkingYears",
                    "PercentSalaryHike", "OverTime", "Attrition_Label"]

    st.dataframe(
        display_df[display_cols].reset_index(drop=True),
        height=450,
        width="stretch",
    )

    # ── Quick summary stats ──
    st.markdown("---")
    st.markdown('<p class="section-header">📈 Summary Statistics</p>', unsafe_allow_html=True)
    stat_cols = ["Age", "MonthlyIncome", "TotalWorkingYears",
                 "YearsAtCompany", "PercentSalaryHike", "JobSatisfaction"]
    st.dataframe(
        fdf[stat_cols].describe().round(2),
        width="stretch",
    )

    # ── Download button ──
    csv_export = fdf[display_cols].to_csv(index=False).encode("utf-8")
    st.download_button(
        label="⬇️  Download Filtered Data as CSV",
        data=csv_export,
        file_name="hr_filtered_data.csv",
        mime="text/csv",
    )

# ─────────────────────────────────────────────
# FOOTER
# ─────────────────────────────────────────────
st.markdown("---")
st.markdown(
    "<p style='text-align:center; color:#4a5568; font-size:0.8rem;'>"
    "HR Attrition Intelligence Dashboard · Built with ❤️ using Streamlit & Plotly"
    "</p>",
    unsafe_allow_html=True,
)