# -*- coding: utf-8 -*-
"""streamlit app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fspcXRsLNLvlGs972-XDNxhPY2OVSHpg
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Load Data
df = pd.read_csv("Palo Alto Networks.csv")

# Sidebar
st.sidebar.title("Filters")

department = st.sidebar.multiselect(
    "Select Department",
    df['Department'].unique(),
    default=df['Department'].unique()
)

overtime = st.sidebar.selectbox(
    "Overtime",
    ['All', 'Yes', 'No']
)

threshold = st.sidebar.slider(
    "Engagement Threshold",
    0.0,
    1.0,
    0.5
)

# Filter Data
filtered_df = df[df['Department'].isin(department)]

  if overtime != 'All':
     filtered_df = filtered_df[
     filtered_df['OverTime'] == overtime
    ]

# Title
st.title("Employee Engagement & Burnout Dashboard")

# KPI Cards
st.metric(
    "Average Engagement",
    round(filtered_df['Engagement_Index'].mean())
)

st.metric(
    "High Burnout Employees",
    len(filtered_df[
        filtered_df['Burnout_Risk'] == 'High'
    ])
)

# Engagement Distribution
fig1 = px.histogram(
    filtered_df,
    x='Engagement_Index',
    nbins=20
)

st.plotly_chart(fig1)

# Burnout Risk
fig2 = px.pie(
    filtered_df,
    names='Burnout_Risk'
)

st.plotly_chart(fig2)

# Role Engagement
role_eng = filtered_df.groupby(
    'JobRole'
)['Engagement_Index'].mean().reset_index()

fig3 = px.bar(
    role_eng,
    x='JobRole',
    y='Engagement_Index'
)

st.plotly_chart(fig3)

# Attrition Comparison
fig4 = px.box(
    filtered_df,
    x='Attrition',
    y='Engagement_Index'
)

st.plotly_chart(fig4)

# Low Engagement Alerts
st.subheader("Low Engagement Employees")

alerts = filtered_df[
    filtered_df['Engagement_Index'] < threshold
]

st.dataframe(alerts[
    [
        'Department',
        'JobRole',
        'Engagement_Index',
        'Burnout_Risk',
        'WorkLifeBalance'
    ]
])
